### ISSUE TITLE
Cannot decompress the dataset

### ISSUE THREAD

**Issue by haotang1995** [liqing-ustc/HINT#1]
Hi, thanks for sharing this interesting dataset & task. I am trying to use it but cannot decode the dataset. The error is as follows:
```
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I have tried two OS, one Ubuntu 20.04 and another macOS Monterey, and also tried commends as `tar -xvf` and `xz -d`. All of them got the same error as above. 

Could you please help with this? Thanks!

**Comment by liqing-ustc** [comment]
Thank you for your interest in our work!

Did you clone the repo correctly? The `dataset.tar.xz` should be around 113MB and you might need [Git LFS](https://git-lfs.com/) to clone it.

If it still does not work, you can also download the dataset from the link: https://github.com/liqing-ustc/HINT/raw/master/data/dataset.tar.xz

**Comment by haotang1995** [comment]
git-lfs works. Thanks!
